### ISSUE TITLE
Python scripts not executable

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-pipeline#100]
[09/46fdcc] process > process_label (test-visium-label.zarr)     [100%] 1 of 1, failed: 1
[84/5687b2] process > process_anndata (test-iss-anndata.zarr)    [100%] 2 of 2, failed: 2
[-        ] process > intersect_anndatas                         -
[-        ] process > ome_zarr_metadata (METADATA.ome.xml, raw)  -
[-        ] process > Build_multimodal_config                    -
ERROR ~ Error executing process > 'process_anndata (test-scrnaseq-anndata.zarr)'

Caused by:
  Process `process_anndata (test-scrnaseq-anndata.zarr)` terminated with an error exit status (126)

Command executed:

  integrate_anndata.py reindex_and_concat         --path test-scrnaseq-anndata.zarr         --offset 2000000         --features celltype

Command exit status:
  126

Command output:
  (empty)

Command error:
  .command.sh: line 2: /webatlas-pipeline/bin/integrate_anndata.py: Permission denied

Work dir:
  /webatlas-pipeline/work/1d/a5a50c277ca11e4b77c90858988b3e

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details

**Comment by BioinfoTongLI** [comment]
I believe it's just that scirpt is executable and it's fixed now? Should we close this? @davehorsfall
