### ISSUE TITLE
Test ISS (in situ sequencing) data to verify the processing of ISS data processing

### ISSUE THREAD

**Issue by ashishjain1988** [haniffalab/webatlas-pipeline#136]
Hi,

I am trying to visualize our ISS dataset by using the iss_template.yaml but not able to see anything on the webatlas portal after processing. Is there any test dataset that I can get to check the format of the data in the h5ad file for this type of data? Also, there is no documentation for this data. Can you please also add that too?

Regards,
Ashish Jain

**Comment by BioinfoTongLI** [comment]
Hi @ashishjain1988, thanks for reaching out!
Would you mind providing more details about the issue? i.e. Did the pipeline fail? If not, could you please provide error logs in the console in your browser when `not able to see anything`.
And yes, we will be adding the doc for ISS. The crucial part is to have id image in label image map the index id in adata.obs. Would you mind confirming if that's the case?
Best,

**Comment by ashishjain1988** [comment]
Hi @BioinfoTongLI,

Thanks! I was able to process the data using the singularity pipeline. Earlier I was trying to use the 10X Visium config file template to process the data but then I found a iss template config file on the pipeline's templates folder. It worked after I followed that format. I think adding documentation about ISS data processing will help.

Thanks,
Ashish
