### ISSUE TITLE
Leftover `.tif` files in the output folder

### ISSUE THREAD

**Issue by prete** [haniffalab/webatlas-pipeline#137]
After running the pipeline (_input data 10x Xenium with `analysis_sw_version: xenium-3.0.0.15`_) I get `anndata.zarr`, `label.zarr`,`raw.zarr` and `config.json`. But there is also a `label.tif` file being created in the output folder that shouldn't be there.

The file seems to be generated [here in process_xenium.py](https://github.com/haniffalab/webatlas-pipeline/blob/209db43f89b43e283c337b6c7781e85d85cfca97/bin/process_xenium.py#L182) and it's probably published by the [Generate_image process](https://github.com/haniffalab/webatlas-pipeline/blob/209db43f89b43e283c337b6c7781e85d85cfca97/main.nf#L253). 

Should that be part of the output?

**Comment by dannda** [comment]
Agree that shouldn't be in the output by default

**Comment by prete** [comment]
Fixed #138
