### ISSUE TITLE
Not able to visualize the data hosted on AWS S3 bucket

### ISSUE THREAD

**Issue by ashishjain1988** [haniffalab/webatlas-pipeline#145]
Hi @dannda @BioinfoTongLI @davehorsfall ,

I am trying to visualize the data hosted on the AWS S3 bucket but the webatlas app is not able to visualize it. I have made the whole test data public and was able to see the content of the config file (https://webatlas-test-bucket.s3.us-east-2.amazonaws.com/DAPI_MUC_h5ad/0.5.1/project1-DAPI-MUC-config-1.json). I would really appreciate your input on this!

Regards,
Ashish Jain

**Comment by dannda** [comment]
It seems to me that you need to enable CORS on the bucket so the webapp can load it. Could you try enabling it?
You can configure it in different ways depending on how you manage your bucket, maybe [these docs](https://docs.aws.amazon.com/AmazonS3/latest/userguide/enabling-cors-examples.html) are helpful.
And setting it to something like
```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedHeader>Access-Control-Allow-Origin</AllowedHeader>
        <AllowedHeader>Authorization</AllowedHeader>
        <AllowedHeader>Content-Length</AllowedHeader>
        <AllowedHeader>Content-MD5</AllowedHeader>
        <AllowedHeader>Content-Type</AllowedHeader>
        <AllowedHeader>Origin</AllowedHeader>
        <ExposeHeader>ETag</ExposeHeader>
    </CORSRule>
</CORSConfiguration>
```

**Comment by ashishjain1988** [comment]
Hi @dannda 

Thank you for this information. I was able to visualize the data after adding these settings to CORS.However, I need to convert to JSON format.

```
[
    {
        "AllowedHeaders": [
            "Access-Control-Allow-Origin",
            "Authorization",
            "Content-Length",
            "Content-MD5",
            "Content-Type",
            "Origin"
        ],
        "AllowedMethods": [
            "GET",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "ETag"
        ]
    }
]
```

We are also trying it on Google cloud bucket. I would be grateful if you can provide some information about that bucket too. We are currently trying out Amazon S3 and Google cloud buckets to host our data.

Regards,
Ashish

**Comment by ashishjain1988** [comment]
Hi @dannda,

I am also trying to make it work on google cloud. Similar to what you suggested previously for AWS S3 bucket I updated the CORS config on the google cloud but it seems like its not working. The JSON file for  Google cloud is a bit different but I am not sure what is the equivalent of "ExposeHeaders" in Google cloud setting. I would really appreciate your input and help on this. Here is my current config file for google cloud

```
[
    {
        "responseHeader": [
            "Access-Control-Allow-Origin",
            "Authorization",
            "Content-Length",
            "Content-MD5",
            "Content-Type",
            "Origin"
        ],
        "method": [
            "GET",
            "HEAD"
        ],
        "origin": [
            "*"
        ]
    }
]
```

Regards,
Ashish
