### ISSUE TITLE
Visium FFPE dataset => multi-slide per h5ad support

### ISSUE THREAD

**Issue by BioinfoTongLI** [haniffalab/webatlas-pipeline#30]
Cell2location processed h5ads tends to have data from multiple slides
Individual slides is identifiable via `adata.obs["sample"]`.
Visium spot metadata are saved in `adata.uns['spatial']` and coordinates in `adata.obsm.spatial`

**Comment by prete** [comment]
I've seen `adata.obs["sample"]` but also `adata.obs["library_id"]` going around for identifiny slides.

**Comment by BioinfoTongLI** [comment]
We may add an extra `entry` to let user provide a multislide h5ad -> split into several h5ads -> generate a csv file with metadata for the conversion pipeline.

**Comment by BioinfoTongLI** [comment]
According to our last chat, it seems that this is no more an issue.
One conversion will only take one `sample` or `library` id. If there are several, we default to the first one.

And if the user wants to convert all, just pass the same h5ad object several times, and each time with a different `sample` or `library` id.
