### ISSUE TITLE
Review and clean all file headers, there are legacy headers containing license declarations that need removing

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-pipeline#59]
We need to review and define standard file headers through the project. There are currently some old legacy headers that were generated by @BioinfoTongLI, possibly from some kind of template. They make licensing declarations we need to remove. We can build a header template using the citation link which is now present in the repo.

**Comment by BioinfoTongLI** [comment]
sure, and the citation link do you mean https://github.com/haniffalab/vitessce-pipeline/blob/main/CITATION.cff ?

**Comment by davehorsfall** [comment]
Done
