### ISSUE TITLE
bioformats2raw breaks with docker (24.0.2) in Nextflow

### ISSUE THREAD

**Issue by BioinfoTongLI** [haniffalab/webatlas-pipeline#60]
bioformats2raw conversion with `--compression` error in the latest nextflow update (22.10.+).
Temporary solution:
Specify `NXF_VER=22.04.5` in the ENV to enforce nextflow version for as walk-around.

**Comment by BioinfoTongLI** [comment]
Oh yea, wanted to save some space while converting...
But actually it was to record which command line went wrong. But I've just tested again and it bugs with and without `--compression`.
It's more a general `bioformats2raw` + 22.10.+ problem

**Comment by prete** [comment]
What compressionare you using `--compression=xxx` ? 
Do you have libblosc installed in your OS? (`sudo apt-get install libblosc1`)


I just tried: 
```
process bioformats2raw {
  debug true

  shell:
  '''
  bioformats2raw --compression=zlib test.ndpi out_zlib.zarr
  '''
}

workflow {
    bioformats2raw()
}
```

and got
```
N E X T F L O W  ~  version 23.04.1
Launching `main.nf` [big_mcclintock] DSL2 - revision: 94a0abcd3d
executor >  local (1)
[c9/3a2a24] process > bioformats2raw [100%] 1 of 1 ✔

Completed at: 22-May-2023 23:59:39
Duration    : 1m 3s
CPU hours   : (a few seconds)
Succeeded   : 1
```

Additional info:
> bioformats2raw version = 0.4.0
> Bio-Formats version = 6.8.0
> OpenJDK Runtime Environment (build 17.0.3-internal+0-adhoc..src)

**Comment by BioinfoTongLI** [comment]
Actually, I have the exact same setting as you. 
I just dug into the detail and realised that it's not the compression or any bf2raw option, but `docker` related.
when I switch to singularity, it works just fine.

**Comment by prete** [comment]
Is this still an issue or we can close it?

**Comment by BioinfoTongLI** [comment]
it still is an issue. And will potentilly stop docker user from running the image conversion step of the pipeline.
I would leave it here for now

**Comment by davehorsfall** [comment]
I can't replicate this using the latest release of the `webatlas-pipeline` from last week (0.4.0).

I'm using:
- Docker version 24.0.7, build afdd53b
- nextflow version 23.10.0.5889
- openjdk version "11.0.20.1" 2023-08-24

@dannda made significant changes and updates to the docker image and dependencies. Could you please try again with the latest version of check if this is still an issue?

**Comment by prete** [comment]
Can't be reprouced, I'll close this we can re-open it if someone else runs into it.
