### ISSUE TITLE
Incorporate RNA spot data processing

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-pipeline#8]

**Comment by davehorsfall** [comment]
Just a TSV.
```
Name	Code	Probability	Unnamed: 0	y_int	x_int
background	0000	1.0	0	1046	5169
Gene1	0000	0.9999998211860657	1	1045	31572
Gene2	0000	0.9999998211860657	2	1056	29285
background	0000	0.9998995065689087	3	1062	28315
background	0000	0.9999998807907104	4	1063	28767
background	0000	0.9999990463256836	5	1073	33282
```
It is to be optimised as you can see (the Unnamed:0  is useless here).
But all the other columns are relatively stable. Tho, this is going to be another community-wise metadata question. How should I name each one of them: should the Name be Gene_name / Ensemble ID or … ? as for all the other columns

**Comment by BioinfoTongLI** [comment]
@dannda would you mind pointing changes in this thread regarding `molecules`? Many thanks!

**Comment by davehorsfall** [comment]
See: https://github.com/haniffalab/webatlas-pipeline/blob/main/bin/process_molecules.py
