### ISSUE TITLE
SeqFish demos

### ISSUE THREAD

**Issue by davehorsfall** [haniffalab/webatlas-pipeline#80]
There are several issues with the integrated SeqFish data demos that need to be discussed. 

- The performance is slow. Selecting genes causes the app to hang for several seconds. 
- The seqFISH dataset alone is showing tile positions rather than cell types (if @BioinfoTongLI does not have cell types for seqFISh alone, either use the annotation from the integrated object or remove the individual seqFISH and scRNAseq modalities of mouse atlas)

**Comment by dannda** [comment]
Couldn't reproduce the issue when testing on a local Vitessce instance (from commit 33c30b5b2b6088ec8cd404fe76c6d56b15d6aa42). Loading and rendering had no problems.

**Comment by dannda** [comment]
Oh no, I just think there was some later development that might have fixed that performance issue after the current Vitessce version we have hosted.
But still unsure where exactly the issue happens so would have to investigate more; I just noticed when I tried to reproduce the issue locally but with Vitessce's main branch

**Comment by BioinfoTongLI** [comment]
this seems to be resolved by bumping vitessce version to v3?
If so, please feel free to close this @davehorsfall @dannda

**Comment by davehorsfall** [comment]
Fixed by bumping `webatlas-app` to `vitessce 3.2.2`.
